### ISSUE TITLE
Exception (`string` and `indent` should be strings in v1.3.5)

### ISSUE THREAD

**Issue by IgnusG** [cenk1cenk2/listr2#3]
The new version `1.3.5` throws the following error on running: 
`'string' and 'indent' should be strings`
<details>
<summary>Stacktrace</summary>
<pre>
/abc/node_modules/indent-string/index.js:6
                throw new TypeError('`string` and `indent` should be strings');
                ^

TypeError: `string` and `indent` should be strings
    at Object.module.exports [as default] (/abc/node_modules/indent-string/index.js:6:9)
    at MultiLineRenderer.formatString (/abc/node_modules/listr2/dist/renderer/default.renderer.js:125:42)
    at MultiLineRenderer.multiLineRenderer (/abc/node_modules/listr2/dist/renderer/default.renderer.js:51:38)
    at MultiLineRenderer.multiLineRenderer (/abc/node_modules/listr2/dist/renderer/default.renderer.js:81:48)
    at Timeout._onTimeout (/abc/node_modules/listr2/dist/renderer/default.renderer.js:25:39)
    at listOnTimeout (internal/timers.js:536:17)
    at processTimers (internal/timers.js:480:7)
</pre>
</details>

#### Specs
- Version: 1.3.5
- Node: 13.3.0

**Comment by IgnusG** [comment]
Maybe this was just an incomplete `npm install` though. I need to double check

**Comment by cenk1cenk2** [comment]
I will try to reproduce. Maybe it is time to write tests.

**Comment by IgnusG** [comment]
I think it was just an incomplete installation. Cannot reproduce it myself after re-installing <kbd>node_modules</kbd>

**Comment by cenk1cenk2** [comment]
Okay then that is cool. As i said i did not had the testing environment and did a quick fix so it can happen.

**Comment by IgnusG** [comment]
No worries! Wanted to type it out so I don't forget any details just in case :)
