### ISSUE TITLE
Failed to run using rollup packaging

### ISSUE THREAD

**Issue by Versirity** [cenk1cenk2/listr2#664]
throw ERROR:

` E:\bin\index.js:5873
            throw err;
            ^

TypeError: Cannot read properties of undefined (reading 'get')
    at exec$1 (E:\bin\index.js:15881:35)
    at E:\bin\index.js:15901:16
    at Array.map (<anonymous>)
    at wrapAnsi_1$1 ( E:\bin\index.js:15901:4)
    at render ( E:\bin\index.js:16059:12)
    at updateRender ( E:\bin\index.js:16685:32)
    at Object.next ( E:\bin\index.js:16693:7)
    at ConsumerObserver.next ( E:\bin\index.js:6054:34)
    at SafeSubscriber.Subscriber._next ( E:\bin\index.js:6021:27)
    at SafeSubscriber.Subscriber.next (E:\bin\index.js:5992:19)`

I see this code in the final output file of rollup:

`// The wrap-ansi module can be invoked in either 'hard' or 'soft' wrap mode
//
// 'hard' will never allow a string to take up more than columns characters
//
// 'soft' allows long words to expand past the column length
const exec$1 = (string, columns, options = {}) => {
	if (options.trim !== false && string.trim() === '') {
		return '';
	}

	let pre = '';
	let ret = '';
	let escapeCode;

	const lengths = wordLengths$1(string);
	let rows = [''];

	for (const [index, word] of string.split(' ').entries()) {
		if (options.trim !== false) {
			rows[rows.length - 1] = rows[rows.length - 1].trimLeft();
		}

		let rowLength = stringWidth$1(rows[rows.length - 1]);

		if (index !== 0) {
			if (rowLength >= columns && (options.wordWrap === false || options.trim === false)) {
				// If we start with a new word but the current row length equals the length of the columns, add a new row
				rows.push('');
				rowLength = 0;
			}

			if (rowLength > 0 || options.trim === false) {
				rows[rows.length - 1] += ' ';
				rowLength++;
			}
		}

		// In 'hard' wrap mode, the length of a line is never allowed to extend past 'columns'
		if (options.hard && lengths[index] > columns) {
			const remainingColumns = (columns - rowLength);
			const breaksStartingThisLine = 1 + Math.floor((lengths[index] - remainingColumns - 1) / columns);
			const breaksStartingNextLine = Math.floor((lengths[index] - 1) / columns);
			if (breaksStartingNextLine < breaksStartingThisLine) {
				rows.push('');
			}

			wrapWord$1(rows, word, columns);
			continue;
		}

		if (rowLength + lengths[index] > columns && rowLength > 0 && lengths[index] > 0) {
			if (options.wordWrap === false && rowLength < columns) {
				wrapWord$1(rows, word, columns);
				continue;
			}

			rows.push('');
		}

		if (rowLength + lengths[index] > columns && options.wordWrap === false) {
			wrapWord$1(rows, word, columns);
			continue;
		}

		rows[rows.length - 1] += word;
	}

	if (options.trim !== false) {
		rows = rows.map(stringVisibleTrimSpacesRight$1);
	}

	pre = rows.join('\n');

	for (const [index, character] of [...pre].entries()) {
		ret += character;

		if (ESCAPES$2.has(character)) {
			const code = parseFloat(/\d[^m]*/.exec(pre.slice(index, index + 4)));
			escapeCode = code === END_CODE$1 ? null : code;
		}

		**const code = ansiStyles$2.codes.get(Number(escapeCode));**

		if (escapeCode && code) {
			if (pre[index + 1] === '\n') {
				ret += wrapAnsi$3(code);
			} else if (character === '\n') {
				ret += wrapAnsi$3(escapeCode);
			}
		}
	}

	return ret;
};`
I modified the code and it works fine.

`const code = ansiStyles$2.codes.get(Number(escapeCode));   =>   const code = 1`

Is there any other way to fix it?  please

**Comment by Versirity** [comment]
https://github.com/rollup/plugins/issues/1398)
